### ISSUE TITLE
Batch convert to PNG

### ISSUE THREAD

**Issue by LandonBoi123** [Garhoogin/NitroPaint#12]
I mean this is a given, it should be included with the program...

**Comment by Garhoogin** [comment]
What exactly is it that you're wanting to batch convert to PNG? I feel like such a feature may be out of scope.

**Comment by minexew** [comment]
wow, entitled much? You might want to check your tone, since you are asking for a favor

**Comment by Garhoogin** [comment]
Since this wasn't elaborated on and I feel that as of now this may be out of scope, I'll be closing this issue.
