### ISSUE TITLE
Some Files Not Made Openable by Issue #3

### ISSUE THREAD

**Issue by opiter09** [Garhoogin/NitroPaint#4]
The vast majority of the graphics files of the game LEGO Battles are now openable by this program with no issues whatsoever. However, a small subset of them, which all have a file size of 49 KB, will not open. Examples include:
- UI / Minigame1_BG_Top.NCGR
- UI / Heroes / A_Defeat.NCBR
- UI / AllinOne / C_Cutscene_1.NCBR
- A surprising quantity of NCGR files in AllinOne for which the corresponding NCBR files open fine

It should be noted that I am using the latest Release, and that these files' palettes all open completely fine.

And, as always, thank you for looking into such a niche game.

**Comment by opiter09** [comment]
Oh! I almost forgot to mention that almost none of the NCGR files in UI / FEPlayerCards open at all. Those files are all 25 KB, so I suspect they all share a different special problem than the files mentioned above.

**Comment by Garhoogin** [comment]
Truly weird indeed, just when I thought we'd figured the whole thing out lol

From the looks of it, it looks like some of these files actually don't employ any compression at all, despite still having the compression header. Perhaps this is indicated by what looks to be negative section sizes. Will be looking into this in the coming days, a solution should be fairly simple I imagine.

Thanks for pointing this out!

**Comment by opiter09** [comment]
great, and take all the time you need

**Comment by Garhoogin** [comment]
I forgot to bring it up yesterday, but I've gotten the other files to load in the program properly, now that it recognizes the negative sizes in these files. I think I will be pushing a release soon, so you should see those changes in effect soon. I'll close the issue for now, but again, feel free to re-open if you continue to have any issues.
