### ISSUE TITLE
Pointers on the NANR are saved wrong

### ISSUE THREAD

**Issue by McKlark** [Garhoogin/NitroPaint#8]
the tool has helped me so much in editing animations 👍 
But everytime a NANR file is saved, the pointers on the animation headers dont mach to the numbers of sub-animations, 
making necessary to fix it with a hex editor.

Also if isnt too much trouble too ask for an NMCR and NMAR viewer/editor. 
Stoping making them from scratch is something I would greatly appreciate 

:)

**Comment by Garhoogin** [comment]
Hey,

Sorry this took so long to get back to you on, but I've addressed the writing wrong NANR offsets to frame data. No idea how that went past me before, but it's fixed now. As for NMAR, I think I will look at adding that some time soon. For now though I'll mark the issue as resolved, but feel free to reopen if you have any issues with it in the future.
